service: auth-server

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  timeout: 60 # optional, in seconds, default is 6
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    PROJECT_ID: ${file(config.json):PROJECT_ID}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get

# endpoints:                                                                                                                                                           
#   GET - https://b9faps374e.execute-api.us-east-2.amazonaws.com/dev/api/get-auth-url
#   GET - https://b9faps374e.execute-api.us-east-2.amazonaws.com/dev/api/token/{code}
#   GET - https://b9faps374e.execute-api.us-east-2.amazonaws.com/dev/api/get-events/{access_token}

# Available on:
#   http://192.168.1.165:8080
#   http://127.0.0.1:8080